### ISSUE TITLE
Missing Ecommerce Data

### ISSUE THREAD

**Issue by gshail** [slirx/magento-google-tag-manager#4]
Hello,
I'm using your plugin on Magento CE 1.9.0.1. I have enabled the module, still I get the following error in Google analytics. I have enabled the website for Ecommerce in Analytics. I also tried to copy the template and layout files in the custom theme directory. But nothing seems to help.

Missing Ecommerce Data
View Website is configured for Ecommerce, but no data is flowing.

Can you please help.
Thanks,
SGu

**Comment by slirx** [comment]
Did you configured Google Analytics in GTM?
